In [3]:
import numpy as np
import util as ut

In [4]:
import numpy as np
A = np.random.rand(2,2)
f = np.random.rand(2,1)
print("Original Random 2x2 Coefficient Matrix A:\n",A)
print("Original Random Vector Matrix B:\n",f)

Original Random 2x2 Coefficient Matrix A:
 [[0.17160271 0.427109  ]
 [0.38550681 0.59327384]]
Original Random Vector Matrix B:
 [[0.97461239]
 [0.0580911 ]]


In [6]:
for val in [3,4,5,6]:
    print(ut.gauss_elimination_pivot(A, f,val))
    print("*"*100)

Executing 2x2 system of equations with Pivot for  3  significant digits!!


Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.172 0.427]
 [0.386 0.593]]
Random Vector Matrix B of  3  significant digits:
 [[0.975]
 [0.058]]
Equations which must be solved based on above matrix:
[0.172*x1 + 0.427*x2] = [[0.975]]
[0.386*x1 + 0.593*x2] = [[0.058]]
Solution is as below:
[-8.80859835  5.83156655]
****************************************************************************************************
Executing 2x2 system of equations with Pivot for  4  significant digits!!


Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.1716 0.4271]
 [0.3855 0.5933]]
Random Vector Matrix B of  4  significant digits:
 [[0.9746]
 [0.0581]]
Equations which must be solved based on above matrix:
[0.1716*x1 + 0.4271*x2] = [[0.9746]]
[0.3855*x1 + 0.5933*x2] = [[0.0581]]
Solution is as below:
[-8.80719474  5.82045099]
*************************************************************************

In [7]:
for val in [3,4,5,6]:
    print(ut.gauss_elimination_without_pivot(A, f,val))
    print("*"*100)

Executing 2x2 system of equations without Pivot for  3  significant digits!!

Random 2x2 Coefficient Matrix A of  3  significant digits:
 [[0.172 0.427]
 [0.386 0.593]]
Random Vector Matrix B of  3  significant digits:
 [[0.975]
 [0.058]]
Equations which must be solved based on above matrix:
[0.172*x1 + 0.427*x2] = [[0.975]]
[0.386*x1 + 0.593*x2] = [[0.058]]

Solution is as below:
[-8.80859835  5.83156655]
****************************************************************************************************
Executing 2x2 system of equations without Pivot for  4  significant digits!!

Random 2x2 Coefficient Matrix A of  4  significant digits:
 [[0.1716 0.4271]
 [0.3855 0.5933]]
Random Vector Matrix B of  4  significant digits:
 [[0.9746]
 [0.0581]]
Equations which must be solved based on above matrix:
[0.1716*x1 + 0.4271*x2] = [[0.9746]]
[0.3855*x1 + 0.5933*x2] = [[0.0581]]

Solution is as below:
[-8.80719474  5.82045099]
*******************************************************************