In [1]:
import numpy as np
import util as ut

In [12]:
row_num = 3
col_num = 3
ITERATIONS = 10
A,B = ut.get_ds_matrix(row_num,col_num,precision=4,method = 'siedel',iterations = 10000)


In [13]:
solution_siedel,iterations_siedel = ut.solve_equations(A,B, n=ITERATIONS,method='siedel')
print('*'*100)
print(solution_siedel)
print('*'*100)
print(iterations_siedel)



    Input A is 
            [[ 0.4642 -0.0314 -0.0444]
 [-0.421  -1.0684  0.0939]
 [ 0.3329 -0.6234 -1.1184]]

    Input B is 
            [0.57127568 0.91674439 0.84064715]

    Input x is 
            [0.48839445 0.61292352 0.24290213]
    
    
[ 1.29536047 -1.34713837  0.38482154]
[ 1.17634987 -1.28776951  0.31630475]
[ 1.17381225 -1.2927914   0.31834863]
[ 1.17366804 -1.29255494  0.3181739 ]
[ 1.17366732 -1.29257001  0.31818209]
[ 1.17366709 -1.2925692   0.31818157]
[ 1.17366709 -1.29256925  0.31818159]
[ 1.17366709 -1.29256925  0.31818159]
[ 1.17366709 -1.29256925  0.31818159]
[ 1.17366709 -1.29256925  0.31818159]
****************************************************************************************************
[ 1.17366709 -1.29256925  0.31818159]
****************************************************************************************************
           1         2         3         4         5         6         7  \
x0  1.295360  1.176350  1.173812  1.173668  1.173667  

In [14]:
solution_jacobi,iterations_jacobi = ut.solve_equations(A,B, n=ITERATIONS,method='jacobi')
print('*'*100)
print(solution_jacobi)
print('*'*100)
print(iterations_jacobi)



    Input A is 
            [[ 0.4642 -0.0314 -0.0444]
 [-0.421  -1.0684  0.0939]
 [ 0.3329 -0.6234 -1.1184]]

    Input B is 
            [0.57127568 0.91674439 0.84064715]

    Input x is 
            [0.9032735  0.69412234 0.76579098]
    
    
[ 1.35086652 -1.14668173 -0.86969176]
[ 1.06991718 -1.4667945   0.2896081 ]
[ 1.15914892 -1.25419817  0.38441342]
[ 1.18259761 -1.28102739  0.29247198]
[ 1.17198874 -1.29834787  0.31440636]
[ 1.17291511 -1.2922397   0.32090304]
[ 1.17394969 -1.29203375  0.31777407]
[ 1.17366434 -1.29271642  0.31796722]
[ 1.17363663 -1.292587    0.31826281]
[ 1.17367366 -1.29255011  0.31818242]
****************************************************************************************************
[ 1.17367366 -1.29255011  0.31818242]
****************************************************************************************************
           1         2         3         4         5         6         7  \
x0  1.350867  1.069917  1.159149  1.182598  1.171989  

In [17]:
solution_simple,iterations_simple = ut.solve_equations(A,B, n=ITERATIONS,method='simple')
print('*'*100)
print(solution_simple)
print('*'*100)
print(iterations_simple)



    Input A is 
            [[ 0.4642 -0.0314 -0.0444]
 [-0.421  -1.0684  0.0939]
 [ 0.3329 -0.6234 -1.1184]]

    Input B is 
            [0.57127568 0.91674439 0.84064715]

    Input x is 
            [0.09128724 0.14773999 0.39636649]
    
    
****************************************************************************************************
[ 1.17366709 -1.29256925  0.31818159]
****************************************************************************************************
None
