In [1]:
import numpy as np
import util as ut

In [2]:
row_num = 3
col_num = 3
ITERATIONS = 10
A,B = ut.get_ds_matrix(row_num,col_num,precision=4,method = 'siedel',iterations = 10000)


In [3]:
solution_siedel,iterations_siedel = ut.solve_equations(A,B, n=ITERATIONS,method='siedel',if_earlystopping=True,early_stopping_per=1)
print('*'*100)
print(solution_siedel)
print('*'*100)
print(iterations_siedel)



    Input A is 
            [[-1.1008 -0.5804  0.4647]
 [-0.1151  0.8544 -0.5586]
 [-0.2315 -0.0333  0.355 ]]

    Input B is 
            [0.92143714 0.71774624 0.12688243]

    Input x is 
            [0.56293186 0.87061193 0.29695677]
    
    
Iterations completed 7, Early stopping value 0
****************************************************************************************************
[-1.22947466  0.41206359 -0.40568798]
****************************************************************************************************
           1         2         3         4         5         6         7
x0 -1.170734 -1.435893 -1.293551 -1.195381 -1.200783 -1.224314 -1.229475
x1  0.876492  0.434914  0.313959  0.380453  0.425657  0.422957  0.412064
x2 -0.323818 -0.538153 -0.456675 -0.386420 -0.385702 -0.401301 -0.405688


In [4]:
solution_jacobi,iterations_jacobi = ut.solve_equations(A,B, n=ITERATIONS,method='jacobi',if_earlystopping=True,early_stopping_per=1)
print('*'*100)
print(solution_jacobi)
print('*'*100)
print(iterations_jacobi)



    Input A is 
            [[-1.1008 -0.5804  0.4647]
 [-0.1151  0.8544 -0.5586]
 [-0.2315 -0.0333  0.355 ]]

    Input B is 
            [0.92143714 0.71774624 0.12688243]

    Input x is 
            [0.87935123 0.45344834 0.7114511 ]
    
    
Iterations completed 10, Early stopping value 2
****************************************************************************************************
[-1.21279857  0.4268738  -0.41124778]
****************************************************************************************************
           1         2         3         4         5         6         7  \
x0 -0.775806 -1.176778 -1.566733 -1.309989 -1.325559 -1.171793 -1.232272   
x1  1.423661  1.371939  0.671753  0.445095  0.270486  0.363950  0.367318   
x2  0.973386 -0.014954 -0.281285 -0.601259 -0.455094 -0.481626 -0.372586   

           8         9        10  
x0 -1.188017 -1.237825 -1.212799  
x1  0.430460  0.410843  0.426874  
x2 -0.411710 -0.376927 -0.411248  


In [5]:
solution_simple,iterations_simple = ut.solve_equations(A,B, n=ITERATIONS,method='simple')
print('*'*100)
print(solution_simple)
print('*'*100)
print(iterations_simple)



    Input A is 
            [[-1.1008 -0.5804  0.4647]
 [-0.1151  0.8544 -0.5586]
 [-0.2315 -0.0333  0.355 ]]

    Input B is 
            [0.92143714 0.71774624 0.12688243]

    Input x is 
            [0.62108538 0.61131804 0.02263713]
    
    
****************************************************************************************************
[-1.22417884  0.41217322 -0.40222423]
****************************************************************************************************
None


In [6]:
A,B = ut.get_nonds_matrix(row_num,col_num,precision=4,method = 'siedel',iterations = 10000)

solution_ndd,iterations_ndd = ut.solve_equations(A,B, n=ITERATIONS,method='siedel')
print('*'*100)
print(solution_ndd)
print('*'*100)
print(iterations_ndd)



    Input A is 
            [[ 0.4988  0.2102 -0.5243]
 [-0.8105  0.6784  0.1274]
 [-1.1112 -0.7524  1.5202]]

    Input B is 
            [0.52452633 0.74018552 0.42060709]

    Input x is 
            [0.0932954  0.07349021 0.14144316]
    
    
Iterations completed 10, Early stopping value 3
****************************************************************************************************
[ 8.12633589  8.8938729  10.61856434]
****************************************************************************************************
           1         2         3         4         5         6         7  \
x0  1.169281  2.484045  3.608463  4.576686  5.409965  6.127138  6.744380   
x1  2.461480  3.617570  4.673006  5.577317  6.355894  7.025967  7.602673   
x2  2.349644  3.882869  5.227142  6.382446  7.376881  8.232746  8.969355   

           8          9         10  
x0  7.275616   7.732830   8.126336  
x1  8.099022   8.526209   8.893873  
x2  9.603326  10.148959  10.618564  
